name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo-dev cmake libffi-dev libssl-dev
          pip3 install --upgrade pip
          pip3 install --user --upgrade buildozer cython

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Log ko 'build.log' file mein save karenge
          buildozer -v android debug > build.log 2>&1
        env:
          ANDROIDSDK_ACCEPT_LICENSE: "1"

      - name: Upload Logs
        if: always() # Ye tab bhi chalega agar build fail ho jaye
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log
