name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        run: |
          # Permissions set karna
          chown -R $(whoami) .
          # Root bypass aur build
          export BUILDOZER_ALLOW_ROOT=1
          buildozer -v android debug
        env:
          ANDROIDSDK_ACCEPT_LICENSE: "1"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
