name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # libtinfo5 ki jagah libtinfo-dev use kar rahe hain
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo-dev cmake libffi-dev libssl-dev
          pip3 install --upgrade pip
          pip3 install --user --upgrade buildozer cython

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer -v android debug
        env:
          ANDROIDSDK_ACCEPT_LICENSE: "1"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
